Truncate passwords before hashing
Bcrypt 5.0.0 raises an error (rather than silently truncating) when
given a long password:
```
ValueError: password cannot be longer than 72 bytes, truncate manually
if necessary (e.g. my_password[:72])
```

This commit follows the advice to manually truncate first.

We need to do this (rather than move to a new hashing algorithm) to
preserve compatibility with the hashed passwords we already have stored
in our database.