always use `_notify_db` fixture in tests
flask says you can't modify the app after the first request has been
served. We were seeing situtations where test_1 would fire off a test
request, but _not_ use any db fixtures. Then test_2 would try and use
the `notify_db` fixture for the first time, which would set up the test
db only at this point and error because this isn't allowed.

this will be a little bit slower if you're running individual tests that
don't use the db, but will prevent these irritating and confusing to
debug test failures where we'd see the following error:

> AssertionError: The setup method 'shell_context_processor' can no
> longer be called on the application. It has already handled its first
> request, any changes will not be applied consistently. Make sure all
> imports, decorators, functions, etc. needed to set up the application
> are done before running it.