Bump to psycopg2==2.9.6
After upgrading from pg11->pg15 locally, we started to see the following
error: `sqlalchemy.exc.OperationalError: (psycopg2.OperationalError)
SCRAM authentication requires libpq version 10 or above`.

A suggested fix for this is to upgrade to psycopg2(-binary)==2.9.6, so
that's what we do here.