Fix requirements (unable to freeze)
For the last few days we've been unable to run `make
freeze-requirements`, getting errors like this:

```
...
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
...
pip._internal.exceptions.InstallationSubprocessError: Getting requirements to build wheel exited with 1

make: *** [freeze-requirements] Error 1
```

From some searches online this seems related to a release of cython3
that just came out, which PyYAML uses.

https://github.com/yaml/pyyaml/issues/724

There is now a new release of PyYAML (6.0.1) that fixes the issue, so
let's bump to that. In order to bump to that, we need to bump awscli,
which means bumping boto3 and botocore.